//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_new_lumiere.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user_role
    {
        public string email { get; set; }
        public Nullable<int> roleid { get; set; }
    }
}
