//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_new_lumiere.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_product
    {
        public string pid { get; set; }
        public string product_id { get; set; }
        public string pid_category { get; set; }
        public string category_code { get; set; }
        public string pid_subcategory { get; set; }
        public string subcategory_code { get; set; }
        public string pid_brand { get; set; }
        public string brand_code { get; set; }
        public string product_desc { get; set; }
        public string product_url { get; set; }
        public Nullable<int> product_size { get; set; }
        public Nullable<double> product_price { get; set; }
        public string product_name { get; set; }
    }
}
